routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group([
    'namespace' => 'App\Http\Controllers',
], function() {
    Route::get('/', 'LoginController@show')->name('welcome');
    Route::get('/login', 'LoginController@show')->name('login');
    Route::post('/login', 'LoginController@postLogin')->name('postLogin');

    Route::get('logout', 'LoginController@logout')->name('logout');

    Route::group([
        'middleware' => 'auth',
    ], function () {
        Route::get('/dashboard', 'MainController@getDashboard')->name('getDashboard');

        Route::get('/venue/{id}', 'MainController@getVenue')->name('getVenue');

        Route::get('/venue/{venue_id}/booking/{table_id}', 'BookingController@getBookingSlots')->name('getBookingSlots');
        Route::post('/bookTable', 'BookingController@bookTable')->name('bookTable');
        Route::get('/newDate', 'BookingController@newDate')->name('newDate');

        Route::get('/bookings', 'BookingController@getBookings')->name('getBookings');
        Route::get('/deleteBooking/{id}', 'BookingController@getDeleteBooking')->name('getDeleteBooking');
    });
});




Route::group([
    'prefix' => '/admin',
    'namespace' => 'App\Http\Controllers\Admin',
    'as' => 'admin.'
], function() {
    Route::group([
        'middleware' => 'guestAdmin:admin',
    ], function () {
        Route::get('/login', 'LoginController@show')->name('login');
        Route::post('login', 'LoginController@validateAuth')->name('validate_login');
    });

    Route::get('logout', 'LoginController@logout')->name('logout');

    Route::group([
        'middleware' => ['authAdmin:admin', 'role:Admin']
    ], function() {
        Route::get('/', 'DashController@index')->name('home');
        Route::get('/dash', 'DashController@index')->name('dash');

        Route::get('/venues', 'VenuesController@getVenues')->name('getVenues');
        Route::get('/venue/{id}', 'VenuesController@getVenue')->name('getVenue');

        Route::get('/addVenue', 'VenuesController@getAddVenue')->name('getAddVenue');
        Route::post('/addVenue', 'VenuesController@postAddVenue')->name('postAddVenue');

        Route::get('/venue/{id}/settings', 'VenuesController@getVenueSettings')->name('getVenueSettings');
        Route::post('/venue/{id}/settings', 'VenuesController@postVenueSettings')->name('postVenueSettings');

        Route::get('/venue/{venue_id}/newTable', 'TablesController@getAddTable')->name('getAddTable');
        Route::post('/venue/{venue_id}/newTable', 'TablesController@postAddTable')->name('postAddTable');
        Route::get('/deleteTable/{id}', 'TablesController@getDeleteTable')->name('getDeleteTable');

        Route::get('/venue/{venue_id}/booking/{table_id}', 'BookingController@getBookingSlots')->name('getBookingSlots');
        Route::post('/bookTable', 'BookingController@bookTable')->name('bookTable');
        Route::get('/newDate', 'BookingController@newDate')->name('newDate');

        Route::get('/bookings', 'BookingController@getBookings')->name('getBookings');
        Route::get('/deleteBooking/{id}', 'BookingController@getDeleteBooking')->name('getDeleteBooking');
    });

});

resources/views/admin/bookingSlots.blade.php
@extends('admin.layout')

@section('content')
    <h2>{{$venue->name}} - {{$table->name}}</h2>

    <p>{{$today}}</p>
    <input
        class="datepicker"
        data-provide="datepicker"
        data-url="{{route('admin.newDate')}}"
        data-venue="{{$venue->id}}"
        data-venue-name="{{$venue->name}}"
        data-table="{{$table->id}}"
        data-table-name="{{$table->name}}"
    >
    <div class="row slots">
        @foreach($slots as $slot)
            <div class="col">
                <div class="card" style="width: 18rem; margin-top: 10px;" id="{{$slot['start']}}">
                    <img class="card-img-top" src="#" alt="{{date('H:i', $slot['start'])}}-{{date('H:i', $slot['end'])}}">
                    <div class="card-body">
                        <h5 class="card-title">{{date('H:i', $slot['start'])}}-{{date('H:i', $slot['end'])}}</h5>
                        <p class="card-text"><i>{{$venue->name}} - {{$table->name}}</i></p>
                        <button type="button"
                                class="btn btn-primary showModalForm"
                                data-table="{{$table->id}}"
                                data-start="{{$slot['start']}}"
                                data-start-text="{{date('H:i', $slot['start'])}}"
                                data-end="{{$slot['end']}}"
                                data-end-text="{{date('H:i', $slot['end'])}}"
                        >
                            Book
                        </button>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
    <div class="modal fade" id="modalForm" >
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{route('admin.bookTable')}}" class="formBooking" method="post">
                    <div class="modal-body">
                        <div class="form-group w-50">
                            <label >Name</label>
                            <input
                                type="text"
                                class="form-control"
                                name="name"
                                id="name"
                                value=""
                                placeholder="Enter name"
                            >
                        </div>
                        <div class="form-group w-50">
                            <label></label>Phone</label>
                            <input
                                type="text"
                                class="form-control"
                                name="phone"
                                id="phone"
                                value=""
                                placeholder="Enter phone number"
                            >
                        </div>
                        <div class="form-group w-50">
                            <label>Email</label>
                            <input
                                type="text"
                                class="form-control"
                                name="email"
                                id="email"
                                value=""
                                placeholder="Enter email"
                            >
                        </div>
                        <input type="hidden" name="table" id="tableField" value="">
                        <input type="hidden" name="start" id="startField" value="">
                        <input type="hidden" name="end" id="endField" value="">
                        <input type="hidden" name="_token" id="token" value="{{ csrf_token() }}" />
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary submitModalForm">Save changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/bookings.blade.php
@extends('layout')

@section('content')
    <h2>Bookings</h2>

    <div class="row">
        @foreach($bookings as $booking)
            <div class="col">
                <div class="card" style="width: 18rem; margin-top: 10px;">
                    <img class="card-img-top" src="#" alt="{{date('H:i', $booking->booking_start)}}-{{date('H:i', $booking->booking_end)}}">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{date('H:i', $booking->booking_start)}}-{{date('H:i', $booking->booking_end)}} {{date('d.m.Y', $booking->booking_start)}}
                        </h5>
                        <p class="card-text"><b>{{$booking->table()->first()->venue()->first()->name}}</b><i> - {{$booking->table()->first()->name}}</i></p>
                        <button data-url="{{route('admin.getDeleteBooking', [$booking->id])}}" class="btn btn-primary deleteBooking">Delete</button>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/admin/dash.blade.php
@extends('admin.layout')

@section('content')
    <h3>Hello, {{$user->name}}</h3>
@endsection

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{$pageName}}</title>
    <link rel="stylesheet" href={{ asset('css/bootstrap/bootstrap.min.css') }}>
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.0/themes/base/jquery-ui.css">
</head>
<body>
    <div class="container" style="margin-top: 20px">
        <div class="row">
            @include('admin.includes.sidemenu')
            <div class="col-8">
                @yield('content')
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <script src="{{ asset('js/bootstrap/bootstrap.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap/bootstrap.esm.min.js') }}"></script>
    <script src="{{ asset('js/main.js') }}"></script>
</body>
</html>

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Login</title>
    <link rel="stylesheet" href={{ asset('css/bootstrap/bootstrap.min.css') }}>
</head>
<body>
<div class="container mt-5">
    @if($errors->any())
        <div class="errorProfilePage">
            <span style="font-size: 25px"><b>Errors: </b></span>
            <ul class="alert-box warning radius">
                @foreach($errors->all() as $error)
                    <li> {{ $error }} </li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{route('admin.validate_login')}}" method="post">
        <div class="form-group w-50">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" name="email" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group w-50">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" name="password" placeholder="Password">
        </div>
        @csrf
        <button type="submit" class="btn btn-primary mt-4">Submit</button>
    </form>
</div>
<script src="{{ asset('js/bootstrap/bootstrap.min.js') }}"></script>
</body>
</html>

resources/views/admin/tableForm.blade.php
@extends('admin.layout')

@section('content')
    @if($errors->any())
        <div class="errorProfilePage">
            <span style="font-size: 25px"><b>Errors: </b></span>
            <ul class="alert-box warning radius">
                @foreach($errors->all() as $error)
                    <li> {{ $error }} </li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{route('admin.postAddTable', [$venue->id])}}" method="post">
        <div class="form-group w-50">
            <label >Name of table</label>
            <input type="text" class="form-control" name="name" placeholder="Enter name">
        </div>
        <div class="form-group w-50">
            <label >Length of booking</label>
            <input type="number" class="form-control" name="lengthOfBooking" placeholder="Enter length">
        </div>
        @csrf
        <button type="submit" class="btn btn-primary mt-4">Submit</button>
    </form>
@endsection

resources/views/admin/venue.blade.php
@extends('admin.layout')

@section('content')
    <h2><a href="{{route('admin.getVenueSettings', [$venue->id])}}">Go to settings</a></h2>

    <h2>Tables</h2>

    <div class="row">
        @foreach($tables as $table)
            <div class="col">
                <div class="card" style="width: 18rem; margin-top: 10px;">
                    <img class="card-img-top" src="#" alt="{{$table->name}}">
                    <div class="card-body">
                        <h5 class="card-title">{{$table->name}}</h5>
                        <p class="card-text"><i>{{$venue->name}}</i></p>
                        <a href="{{route('admin.getBookingSlots', [$venue->id, $table->id])}}" class="btn btn-primary">Book</a>
                    </div>
                    <button type="button" class="deleteTable" data-url="{{route('admin.getDeleteTable', [$table->id])}}" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        @endforeach
            <div class="col">
                <div class="card" style="width: 18rem; margin-top: 10px;">
                    <img class="card-img-top" src="#" alt="+">
                    <div class="card-body">
                        <h5 class="card-title">Add a new table</h5>
                        <p class="card-text"><i>{{$venue->name}}</i></p>
                        <a href="{{route('admin.getAddTable', [$venue->id])}}" class="btn btn-primary">Add</a>
                    </div>
                </div>
            </div>
    </div>
@endsection

resources/views/admin/venueForm.blade.php
@extends('admin.layout')

@section('content')
    @if($errors->any())
        <div class="errorProfilePage">
            <span style="font-size: 25px"><b>Errors: </b></span>
            <ul class="alert-box warning radius">
                @foreach($errors->all() as $error)
                    <li> {{ $error }} </li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{route('admin.postAddVenue')}}" method="post">
        <div class="form-group w-50">
            <label >Name of venue</label>
            <input type="text" class="form-control" name="name" placeholder="Enter name">
        </div>
        @csrf
        <button type="submit" class="btn btn-primary mt-4">Submit</button>
    </form>
@endsection

resources/views/admin/venueSettings.blade.php
@extends('admin.layout')

@section('content')
    @if($errors->any())
        <div class="errorProfilePage">
            <span style="font-size: 25px"><b>Errors: </b></span>
            <ul class="alert-box warning radius">
                @foreach($errors->all() as $error)
                    <li> {{ $error }} </li>
                @endforeach
            </ul>
        </div>
    @endif
    @foreach($days as $day_id=>$day)
        <h4>{{$day}}</h4>
        <form action="{{route('admin.postVenueSettings', [$venue->id])}}" method="post">
            <div class="form-group w-50">
                <label >Opening time</label>
                <input
                    type="text"
                    class="form-control"
                    name="openingTime"
                    value="{{$venue->openingTime()->where('day', $day_id)->first()->opening_time}}"
                    placeholder="Enter time"
                >
            </div>
            <div class="form-group w-50">
                <label >Closing time</label>
                <input
                    type="text"
                    class="form-control"
                    name="closingTime"
                    value="{{$venue->openingTime()->where('day', $day_id)->first()->closing_time}}"
                    placeholder="Enter time"
                >
            </div>
            <div class="form-check">
                <input
                    type="checkbox"
                    class="form-check-input"
                    name="isWorking"
                    @if($venue->openingTime()->where('day', $day_id)->first()->is_working) checked="checked" @endif
                >
                <label class="form-check-label" for="exampleCheck1">Is it working</label>
            </div>
            <input type="hidden" name="day" value="{{$day_id}}">
            @csrf
            <button type="submit" class="btn btn-primary mt-4">Submit</button>
        </form>
    @endforeach
@endsection

resources/views/admin/venues.blade.php
@extends('admin.layout')

@section('content')
    <h2>Venues</h2>

    <div class="container">
        <div class="row">
            @foreach($venues as $venue)
                <div class="col">
                    <div class="card" style="width: 18rem; margin-top: 10px;">
                        <img class="card-img-top" src="#" alt="{{$venue->name}}">
                        <div class="card-body">
                            <h5 class="card-title">{{$venue->name}}</h5>
            {{--                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>--}}
                            <a href="{{route('admin.getVenue', [$venue->id])}}" class="btn btn-primary">View Tables</a>
                        </div>
                    </div>
                </div>
            @endforeach
            <div class="col">
                <div class="card" style="width: 18rem; margin-top: 10px;">
                    <img class="card-img-top" src="#" alt="+">
                    <div class="card-body">
                        <h5 class="card-title">Add Venue</h5>
                        {{--                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>--}}
                        <a href="{{route('admin.getAddVenue')}}" class="btn btn-primary">Go</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection